"""add object_type to satellites

Revision ID: 1eb1a3d4cc4d
Revises: afa7dcfa4fe2
Create Date: 2026-03-13 22:27:31.237382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1eb1a3d4cc4d'
down_revision: Union[str, Sequence[str], None] = 'afa7dcfa4fe2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('satellites', sa.Column('object_type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('satellites', 'object_type')
    # ### end Alembic commands ###
