"""initial schema

Revision ID: afa7dcfa4fe2
Revises: 
Create Date: 2026-03-13 22:05:06.273960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afa7dcfa4fe2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('operator_type', sa.String(length=50), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('launches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('launch_date', sa.DateTime(), nullable=True),
    sa.Column('launch_site', sa.String(length=255), nullable=True),
    sa.Column('vehicle', sa.String(length=255), nullable=True),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('payload_description', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('source_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_id', name='uq_launch_source')
    )
    op.create_table('satellites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('norad_id', sa.Integer(), nullable=True),
    sa.Column('intl_designator', sa.String(length=20), nullable=True),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('launch_id', sa.Integer(), nullable=True),
    sa.Column('purpose', sa.String(length=100), nullable=True),
    sa.Column('constellation', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('source_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['launch_id'], ['launches.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('norad_id')
    )
    op.create_table('orbits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('satellite_id', sa.Integer(), nullable=True),
    sa.Column('orbit_class', sa.String(length=10), nullable=True),
    sa.Column('apogee_km', sa.Float(), nullable=True),
    sa.Column('perigee_km', sa.Float(), nullable=True),
    sa.Column('inclination_deg', sa.Float(), nullable=True),
    sa.Column('period_min', sa.Float(), nullable=True),
    sa.Column('epoch', sa.DateTime(), nullable=True),
    sa.Column('tle_line1', sa.String(length=70), nullable=True),
    sa.Column('tle_line2', sa.String(length=70), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['satellite_id'], ['satellites.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('satellite_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orbits')
    op.drop_table('satellites')
    op.drop_table('launches')
    op.drop_table('operators')
    # ### end Alembic commands ###
