"""add launch_window to launches table

Revision ID: ed6655be8857
Revises: 5e6422da0f8c
Create Date: 2026-03-30 18:26:25.896469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed6655be8857'
down_revision: Union[str, Sequence[str], None] = '5e6422da0f8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('launches', sa.Column('launch_window', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('launches', 'launch_window')
    # ### end Alembic commands ###
